production:
  database: ${DATABASE_NAME:-canvas_production}
  username: ${DATABASE_USER:-canvas}
  password: ${DATABASE_PASSWORD:-canvas}
  host: ${DATABASE_HOST:-localhost}
  port: ${DATABASE_PORT:-5432}
  adapter: postgresql
  encoding: utf8
