production:
  &default # replace this with a random string of at least 20 characters
  encryption_key: ${ENCRYPTION_KEY:-facdd3a131ddd8988b14f6e4e01039c93cfa0160facdd3a131ddd8988b14f6e4e01039c93cfa0160}
  lti_iss: "https://canvas.instructure.com"
