name: Canvas Base Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - "base/**/*"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      CACHE_LOCATION: /tmp/.buildx-cache
      REGISTRY: ghcr.io
    defaults:
      run:
        working-directory: base
    steps:
      - uses: actions/checkout@v3

      # cache docker
      - uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_LOCATION }}
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/beohoang98/canvas-lms-base:latest
          cache-from: type=local,src=${{ env.CACHE_LOCATION }}
          cache-to: type=local,mode=max,dest=${{ env.CACHE_LOCATION }}
