name: Docker Image CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - examples/**

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
      max-parallel: 2
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Replace env
      run: |
        TAG=${{ matrix.platform }}
        TAG=${TAG//linux\//}
        echo "TAG=$TAG" >> $GITHUB_ENV
    
    - name: Build and Push
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: beohoang98/canvas-lms-docker:${{ env.TAG }}
        platforms: ${{ matrix.platform }}
        cache-from: beohoang98/canvas-lms-docker:${{ env.TAG }}
