name: Docker Image CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - examples/**

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CACHE_LOCATION: /tmp/.buildx-cache
      REGISTRY: ghcr.io
    steps:
    - uses: actions/checkout@v3

    # cache docker
    - uses: actions/cache@v2
      with:
        path: ${{ env.CACHE_LOCATION }}
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ${{ env.REGISTRY }}/beohoang98/canvas-lms-docker:latest
        cache-from: type=local,src=${{ env.CACHE_LOCATION }}
        cache-to: type=local,dest=${{ env.CACHE_LOCATION }}

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run docker-compose example
      run: |
        cd examples/up-with-migration
        docker compose pull
        docker compose up -d --wait
        docker compose down
